In [2]:
import pandas as pd
import glob
import os
import numpy as np
import pickle
import statistics
import community
import matplotlib as mlp
# mlp.use("Qt5Agg")
import matplotlib.pyplot as plt
%matplotlib inline
import networkx as nx

import analysis as an
import pandas as pd


import numpy as np
import seaborn as sns

from scipy import stats 
import scipy
import pprint as pp
import bct as bct

In [3]:
def zscore(col):
    col_z = (col - col.mean())/col.std(ddof=0)
    return(col_z)

In [4]:
p='/Users/gracer/Google Drive/HCP/HCP_graph/1200/'
atlas=pd.read_csv(os.path.join(p,'brains','atlas.csv'), sep=',')


In [5]:
labels = pd.read_csv('/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets/tmp/mod_labels.csv', sep=',')

In [6]:
basepath='/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets/'

In [7]:
# this is a dataframe
latest_file=an.find_latest(os.path.join(basepath,'tmp'),'6_*')
submod_dict=an.onetoughjar(latest_file)

/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets/tmp/6_submod_dict_09-15-2020_03-49-48


In [8]:
# this is the graph
latest_file=an.find_latest(os.path.join(basepath,'tmp'),'5_*')
summary_dict=an.onetoughjar(latest_file)

/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets/tmp/5_summary_dict_09-15-2020_03-49-44


In [34]:
# this is the graph
latest_file=an.find_latest(os.path.join(basepath,'tmp'),'7_*')
subgraph_dict=an.onetoughjar(latest_file)

/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets/tmp/7_subgraph_dict_09-17-2020_08-55-55


In [40]:
# this is the graph
latest_file=an.find_latest(os.path.join(basepath,'tmp'),'10_*')
subedge_dict=an.onetoughjar(latest_file)

/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets/tmp/10_subedge_dict_09-16-2020_10-33-42


In [52]:
subedge_dict['no'].keys()

dict_keys(['mean_FC', 'graphs', 'clustering_coeff', 'btn_centrality', 'PC', 'modules', 'comm_graph'])

In [55]:
test = dict(subedge_dict['no']['graphs']['138837'].nodes(data=True))

In [59]:
pd.DataFrame.from_dict(test, orient='index')

centrality  clustering           PC  modules
0     0.002873    0.701201   -78.259731        0
1     0.005057    0.658915    -2.020314        1
2     0.002237    0.726984  -977.510148        2
3     0.002636    0.710924   -79.544556        2
4     0.006885    0.615510   -46.214469        3
..         ...         ...          ...      ...
95    0.005045    0.549020    -3.856371        2
96    0.010323    0.505051  -148.544270        2
97    0.008284    0.538055   -31.817588        7
98    0.004751    0.743434   -27.350680        5
99    0.008315    0.655686 -3505.400985        5

[100 rows x 4 columns]

In [69]:
_dfs=[]
for group, data in subedge_dict.items():
    print(group)
    for sub, dat in data['graphs'].items():
        print(sub)
        tmp = pd.DataFrame.from_dict(test, orient='index')
        tmp['subject'] = sub
        tmp['group'] = group
        tmp['IC'] = tmp.index
        tmp['IC']=tmp['IC']+1
        _dfs.append(tmp)
total = pd.concat(_dfs)

09-17-2020_09-28-57 NumExpr defaulting to 4 threads. 


no
200513
379657
125222
217429
157437
979984
256540
281135
117324
140319
285446
729557
130821
145127
529549
188145
645551
146331
137027
309636
168139
198451
152427
173536
704238
186444
371843
105620
475855
180735
154734
361234
129634
174437
835657
245333
178950
210112
194847
185846
148840
135629
378857
553344
120717
138332
138534
169545
135225
561444
622236
238033
206222
204420
117122
178849
109830
228434
173940
208125
102109
381543
571144
499566
465852
386250
180432
350330
227432
448347
555651
459453
366042
156536
128127
101107
185341
173637
101915
214726
162228
198855
122620
837560
144125
849971
144428
112112
131419
580347
142828
200917
749361
172534
199352
107321
316633
176037
558960
616645
654754
160123
349244
361941
186040
157942
113619
190031
432332
101309
185038
727553
158843
479762
149842
138231
397154
336841
114318
120414
175742
153429
715041
210011
567759
132017
802844
122317
250932
214423
285345
130013
111716
175338
146533
173738
211417
208226
180937
114823
176441
173435
148

In [70]:
total

centrality  clustering           PC  modules subject group   IC
0     0.002873    0.701201   -78.259731        0  200513    no    1
1     0.005057    0.658915    -2.020314        1  200513    no    2
2     0.002237    0.726984  -977.510148        2  200513    no    3
3     0.002636    0.710924   -79.544556        2  200513    no    4
4     0.006885    0.615510   -46.214469        3  200513    no    5
..         ...         ...          ...      ...     ...   ...  ...
95    0.005045    0.549020    -3.856371        2  212318    ob   96
96    0.010323    0.505051  -148.544270        2  212318    ob   97
97    0.008284    0.538055   -31.817588        7  212318    ob   98
98    0.004751    0.743434   -27.350680        5  212318    ob   99
99    0.008315    0.655686 -3505.400985        5  212318    ob  100

[34300 rows x 7 columns]

In [71]:
latest_file=an.find_latest(os.path.join(basepath,'tmp'),'demo*')
demo_dict=an.onetoughjar(latest_file)

/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets/tmp/demo_dict_11-13-2019_02-07-22


In [73]:
demo_dict['NR'].keys()

dict_keys([100004, 100206, 101006, 101107, 101309, 101410, 101612, 101915, 102008, 102109, 102513, 102614, 102715, 103111, 103212, 104113, 105216, 105620, 105923, 106218, 107119, 107220, 107321, 107523, 107725, 108121, 108525, 108828, 109325, 109830, 110411, 110613, 111716, 112112, 112314, 112920, 113215, 113619, 113821, 114318, 114419, 114621, 114823, 115219, 116120, 117122, 117324, 117728, 117930, 118124, 118528, 118730, 118932, 119025, 119126, 119732, 120010, 120414, 120515, 120717, 121315, 121416, 121618, 121719, 122317, 122418, 122519, 122620, 123117, 123420, 124220, 125222, 126628, 127327, 127630, 127933, 128026, 128127, 128329, 129129, 129634, 130013, 130821, 131419, 132017, 132320, 133221, 133827, 133928, 134223, 134324, 135225, 135427, 135629, 136126, 136227, 136631, 136732, 136833, 137027, 137229, 137936, 138130, 138231, 138332, 138534, 138837, 139233, 140319, 140723, 140925, 141624, 142424, 142828, 143527, 144125, 144428, 144832, 145127, 145531, 146331, 146533, 146836, 14703

In [78]:
demo_df = pd.DataFrame.from_dict(demo_dict['NR'], orient='index')

In [83]:
demo_df['subject'] = demo_df.index
demo_df.reset_index(inplace = True)

In [84]:
demo_df

index  Age_in_Yrs ZygosityGT                                  Race  \
0    100004          24                                            White   
1    100206          27                                            White   
2    101006          35                             Black or African Am.   
3    101107          22                                            White   
4    101309          29                             Black or African Am.   
..      ...         ...        ...                                   ...   
410  947668          30                                            White   
411  970764          22             Asian/Nat. Hawaiian/Othr Pacific Is.   
412  979984          34                             Black or African Am.   
413  991267          30                                            White   
414  994273          30                                            White   

               Ethnicity    BMI  HbA1C  Hypothyroidism  Hyperthyroidism  \
0    Not Hispanic/Latino  25.49    5.4             NaN              NaN   
1    Not Hispanic/Latino  26.64    NaN             NaN              NaN   
2    Not Hispanic/Latino  30.27    6.0             0.0              0.0   
3    Not Hispanic/Latino  21.13    NaN             NaN              NaN   
4    Not Hispanic/Latino  22.20    5.4             NaN              NaN   
..                   ...    ...    ...             ...              ...   
410      Hispanic/Latino  43.76    NaN             0.0              0.0   
411  Not Hispanic/Latino  25.12    NaN             0.0              0.0   
412  Not Hispanic/Latino  24.23    5.6             0.0              0.0   
413  Not Hispanic/Latino  27.34    5.2             NaN              NaN   
414  Not Hispanic/Latino  25.87    5.0             NaN              NaN   

     OtherEndocrn_Prob  Mother_ID  Father_ID ov_ob  subject  
0                  NaN      52259      82122    ov   100004  
1                  NaN      56037      85858    ov   100206  
2                  0.0      51283      81149    ob   101006  
3                  NaN      51969      81833    no   101107  
4                  NaN      52385      82248    no   101309  
..                 ...        ...        ...   ...      ...  
410                0.0      52040      81904    ob   947668  
411                0.0      54609      84431    ov   970764  
412                0.0      52164      99980    no   979984  
413                NaN      51639      81503    ov   991267  
414                NaN      52364      82227    ov   994273  

[415 rows x 14 columns]

In [90]:
demo_df["subject"]=pd.to_numeric(demo_df["subject"])
total["subject"]=pd.to_numeric(total["subject"])

In [91]:
pd.merge(demo_df, total, on="subject")

index  Age_in_Yrs ZygosityGT   Race            Ethnicity    BMI  \
0      100206          27             White  Not Hispanic/Latino  26.64   
1      100206          27             White  Not Hispanic/Latino  26.64   
2      100206          27             White  Not Hispanic/Latino  26.64   
3      100206          27             White  Not Hispanic/Latino  26.64   
4      100206          27             White  Not Hispanic/Latino  26.64   
...       ...         ...        ...    ...                  ...    ...   
34295  994273          30             White  Not Hispanic/Latino  25.87   
34296  994273          30             White  Not Hispanic/Latino  25.87   
34297  994273          30             White  Not Hispanic/Latino  25.87   
34298  994273          30             White  Not Hispanic/Latino  25.87   
34299  994273          30             White  Not Hispanic/Latino  25.87   

       HbA1C  Hypothyroidism  Hyperthyroidism  OtherEndocrn_Prob  Mother_ID  \
0        NaN             NaN              NaN                NaN      56037   
1        NaN             NaN              NaN                NaN      56037   
2        NaN             NaN              NaN                NaN      56037   
3        NaN             NaN              NaN                NaN      56037   
4        NaN             NaN              NaN                NaN      56037   
...      ...             ...              ...                ...        ...   
34295    5.0             NaN              NaN                NaN      52364   
34296    5.0             NaN              NaN                NaN      52364   
34297    5.0             NaN              NaN                NaN      52364   
34298    5.0             NaN              NaN                NaN      52364   
34299    5.0             NaN              NaN                NaN      52364   

       Father_ID ov_ob  subject  centrality  clustering           PC  modules  \
0          85858    ov   100206    0.002873    0.701201   -78.259731        0   
1          85858    ov   100206    0.005057    0.658915    -2.020314        1   
2          85858    ov   100206    0.002237    0.726984  -977.510148        2   
3          85858    ov   100206    0.002636    0.710924   -79.544556        2   
4          85858    ov   100206    0.006885    0.615510   -46.214469        3   
...          ...   ...      ...         ...         ...          ...      ...   
34295      82227    ov   994273    0.005045    0.549020    -3.856371        2   
34296      82227    ov   994273    0.010323    0.505051  -148.544270        2   
34297      82227    ov   994273    0.008284    0.538055   -31.817588        7   
34298      82227    ov   994273    0.004751    0.743434   -27.350680        5   
34299      82227    ov   994273    0.008315    0.655686 -3505.400985        5   

      group   IC  
0        ov    1  
1        ov    2  
2        ov    3  
3        ov    4  
4        ov    5  
...     ...  ...  
34295    ov   96  
34296    ov   97  
34297    ov   98  
34298    ov   99  
34299    ov  100  

[34300 rows x 20 columns]

In [77]:
x

Age_in_Yrs ZygosityGT                                  Race  \
100004          24                                            White   
100206          27                                            White   
101006          35                             Black or African Am.   
101107          22                                            White   
101309          29                             Black or African Am.   
...            ...        ...                                   ...   
947668          30                                            White   
970764          22             Asian/Nat. Hawaiian/Othr Pacific Is.   
979984          34                             Black or African Am.   
991267          30                                            White   
994273          30                                            White   

                  Ethnicity    BMI  HbA1C  Hypothyroidism  Hyperthyroidism  \
100004  Not Hispanic/Latino  25.49    5.4             NaN              NaN   
100206  Not Hispanic/Latino  26.64    NaN             NaN              NaN   
101006  Not Hispanic/Latino  30.27    6.0             0.0              0.0   
101107  Not Hispanic/Latino  21.13    NaN             NaN              NaN   
101309  Not Hispanic/Latino  22.20    5.4             NaN              NaN   
...                     ...    ...    ...             ...              ...   
947668      Hispanic/Latino  43.76    NaN             0.0              0.0   
970764  Not Hispanic/Latino  25.12    NaN             0.0              0.0   
979984  Not Hispanic/Latino  24.23    5.6             0.0              0.0   
991267  Not Hispanic/Latino  27.34    5.2             NaN              NaN   
994273  Not Hispanic/Latino  25.87    5.0             NaN              NaN   

        OtherEndocrn_Prob  Mother_ID  Father_ID ov_ob  
100004                NaN      52259      82122    ov  
100206                NaN      56037      85858    ov  
101006                0.0      51283      81149    ob  
101107                NaN      51969      81833    no  
101309                NaN      52385      82248    no  
...                   ...        ...        ...   ...  
947668                0.0      52040      81904    ob  
970764                0.0      54609      84431    ov  
979984                0.0      52164      99980    no  
991267                NaN      51639      81503    ov  
994273                NaN      52364      82227    ov  

[415 rows x 12 columns]

In [10]:
part = pd.DataFrame.from_dict(summary_dict['no']['modules']['partition'], orient='index', columns = ['module'])


Making an edge data frame

In [ ]:
edges = {}

for group, stuff in summary_dict.items():
    print(group)
    _df = nx.to_pandas_edgelist(stuff['comm_graph'])
    _df.loc[(_df['source'] == _df['target']), 'weight'] = 0

    _df['group']=group
    edges[group]=_df

edge_df=pd.concat(list(edges.values()))

In [ ]:
edge_df['z_weight']=an.zscore(edge_df['weight'])

# Set normalized edge as an get_edge_attributes
for k,v in update_dict.items():
    test=edge_df[edge_df['group']==k]
    keyz = list(zip(test['source'],test['target']))
    values=test['z_weight']
    up_dict={}
    for i in range(len(keyz)):
        up_dict[keyz[i]]={'z_edge':values[i]}
    nx.set_edge_attributes(v['comm_graph'], up_dict)


In [ ]:
edge_df

Checking the save dict to calculcate differences in edges 

In [ ]:
# this is a dataframe
latest_file=an.find_latest(os.path.join(basepath,'tmp'),'3_*')
save_dict=an.onetoughjar(latest_file)

In [1]:
for group, values in save_dict['NR'].items():
    print(group)
    values['modules'] = summary_dict[group]['modules']['partition']
    for sub, graph in values['graphs'].items():
        print(sub)
        G = graph
        modules = summary_dict[group]['modules']['partition']
        nx.set_node_attributes(G, modules, 'modules')

NameError: name 'save_dict' is not defined

In [ ]:
save_dict['NR']['no'].keys()

In [ ]:
edges = {}

for group, stuff in save_dict['NR'].items():
    print(group)
    for sub, graph in stuff['graphs'].items():
        print(sub)
        _df = nx.to_pandas_edgelist(graph)
        _df.loc[(_df['source'] == _df['target']), 'weight'] = 0

        _df['group']=group
        edges[group]=_df

sub_edge_df=pd.concat(list(edges.values()))

In [ ]:
sub_edge_df = sub_edge_df[sub_edge_df['source'] != sub_edge_df['target']]

In [ ]:
sub_edge_df.to_csv(os.path.join(basepath,'tmp','sub_edge_data.csv'), sep=',')

In [ ]:
sub_edge_df['z_weight']=an.zscore(sub_edge_df['weight'])

In [ ]:
# Set normalized edge as an get_edge_attributes
for group,v in save_dict['NR'].items():
    for sub, graph in v['graphs'].items():
        test=sub_edge_df[sub_edge_df['group']==group]
        keyz = list(zip(test['source'],test['target']))
        values=test['z_weight']
        up_dict={}
        for i in range(len(keyz)):
            up_dict[keyz[i]]={'z_edge':values[i]}
        nx.set_edge_attributes(graph, up_dict)


Make individual comm graphs

In [ ]:
save_dict['NR']['no']['comm_graph']['200513'].edges(data=True)

In [ ]:
# Make community graph
for group,v in save_dict['NR'].items():
    print(group)
    v.update(comm_graph = {})
    for sub, data in v['graphs'].items():
        print(sub)
        comm_graph = community.induced_graph(v['modules'], data)
        v['comm_graph'][sub] = comm_graph


In [ ]:
def cal_edges(dic, basepath, group):
    edges = {}
    for sub, graph in dic.items():
        print(sub)
        _df = nx.to_pandas_edgelist(graph)
        _df.loc[(_df['source'] == _df['target']), 'weight'] = 0
        _df = _df[_df['source'] != _df['target']]
        _df['group']=group
        _df['z_weight']=an.zscore(_df['weight'])
        edges[sub]=_df
    return(edges)
    
    


    

In [ ]:
save_dict['NR']['no']['comm_graph']['157437']

In [ ]:
tmp_dict = {'no':{}, 'ov': {}, 'ob': {}}
for group, dat in save_dict['NR'].items():
    print(group)
    x=cal_edges(dat['comm_graph'], basepath, group)
    tmp_dict[group]=pd.concat(list(x.values()))


In [ ]:
tmp_dict['ob']

In [ ]:
sub_comm_edge_df=pd.concat(list(tmp_dict.values()))


In [ ]:
sub_comm_edge_df.to_csv(os.path.join(basepath,'tmp','sub_comm_edge_data.csv'), sep=',')

In [ ]:
edges = {}

for group, stuff in save_dict['NR'].items():
    print(group)
    for sub, graph in stuff['graphs'].items():
        print(sub)
        _df = nx.to_pandas_edgelist(graph)
        _df.loc[(_df['source'] == _df['target']), 'weight'] = 0

        _df['group']=group
        edges[group]=_df

sub_edge_df=pd.concat(list(edges.values()))
sub_edge_df = sub_edge_df[sub_edge_df['source'] != sub_edge_df['target']]
sub_edge_df['z_weight']=an.zscore(sub_edge_df['weight'])
sub_edge_df.to_csv(os.path.join(basepath,'tmp','sub_edge_data.csv'), sep=',')


In [ ]:
# Set normalized edge as an get_edge_attributes
for group,v in save_dict['NR'].items():
    for sub, graph in v['graphs'].items():
        test=sub_edge_df[sub_edge_df['group']==group]
        keyz = list(zip(test['source'],test['target']))
        values=test['z_weight']
        up_dict={}
        for i in range(len(keyz)):
            up_dict[keyz[i]]={'z_edge':values[i]}
        nx.set_edge_attributes(graph, up_dict)


In [ ]:
#an.adillyofapickle('/Users/gracer/Google Drive/HCP/HCP_graph/1200/datasets',save_dict['NR'],'10_subedge_dict')

In [11]:
def mod_loc(group, module): 
    columns=['Index','area', 'label']
    data = []
    part = pd.DataFrame.from_dict(summary_dict[group]['modules']['partition'], orient='index', columns = ['module'])
    x = part.loc[part['module'] == module].index
    for item in x:
        data.append(labels[['Index','area', 'label']].loc[labels['Index'][item]])    
    df = pd.DataFrame(data, columns=columns)
    return(df)

In [12]:
mod_loc('no', 0)

Index            area                label
73     20         Smmouth          L_SMmouth_1
58      6  FrontoParietal  R_FrontoParietal_10
72     46          Smhand           L_SMhand_6
84      2          Visual           L_Visual_9

In [13]:
aes_dict={'no':{},
          'ov':{},
          'ob':{}}
for group, stuff in summary_dict.items():
    print(group)
    G=stuff['comm_graph']
    aes_dict[group]=an.aesthetics(G,15000,100, 'sans-serif', 'Bold', 'z_edge', (80,50), 1)

no
8
ov
9
ob
9


In [14]:
for key, graph in summary_dict.items():
    print(key)
    G=graph['comm_graph']
    aes=aes_dict[key]
    an.module_fig(G,'%s z-score'%key, basepath, aes)

no
8
8
[0.4375 1.3125 2.1875 3.0625 3.9375 4.8125 5.6875 6.5625]
ov
9
9
[0.44444444 1.33333333 2.22222222 3.11111111 4.         4.88888889
 5.77777778 6.66666667 7.55555556]
ob
9
9
[0.44444444 1.33333333 2.22222222 3.11111111 4.         4.88888889
 5.77777778 6.66666667 7.55555556]


In [ ]:
groups = ['no','ov','ob']
mods = [2,4,0,5,2,6]
IC_=[11,16, 27, 35, 54, 58, 85]
for group in groups:
    for mod in mods:
        for x in IC_:
            if x in list(subgraph_dict[group][mod].nodes()):
                print('for %s in mod %i and node %i'%(group, mod, x))
                print(subgraph_dict[group][mod].nodes(data=True)[x])

In [15]:
def aesthetics(graph, node_size, font_size, font_family, font_weight, edge_att, plot_size, mod):
    aes={'general':{},
         'nodes':{},
         'edges':{}}
    # nodes
    color = np.array(list(graph.nodes))
    color = np.array(color)
    n_color=len(list(set(color)))
    print(n_color)
    aes['nodes']['color'] = color
    aes['nodes']['colormap'] = ['Set3', n_color]
    aes['nodes']['n_color'] = n_color
    aes['nodes']['max'] = float(color.max())
    aes['nodes']['min'] = float(color.min())
    aes['nodes']['font_size'] = int(font_size)
    aes['nodes']['font_family'] = font_family
    aes['nodes']['font_weight'] = font_weight
    aes['nodes']['node_size'] = int(node_size)
    #edges
    aes['edges']['colormap'] = plt.cm.gist_rainbow
    edges,weights = zip(*nx.get_edge_attributes(graph,edge_att).items())
    weights=np.array(weights)
    aes['edges']['width mod'] = mod
    aes['edges']['min'] = weights.min()
    aes['edges']['max'] = weights.max()
    # General
    aes['general']['plot_size']=plot_size #tuple 80,50
    return(aes)

In [16]:
from mpl_toolkits.axes_grid1.inset_locator import inset_axes

def basic_graph(graph, scl, FONT, metric, size, tile, basepath, bmi, mod):
    #threshold
    e,w = zip(*nx.get_edge_attributes(graph, 'weight').items())
    purr=np.percentile(w, tile)
    g=an.threshold2(graph,purr)
    # style
    fig = plt.figure(figsize = size)
    ax1 = plt.subplot(111, aspect = 'equal')
    plt.subplots_adjust(left=0.25, bottom=0, right=0.75, top=1, wspace=0.2, hspace=0)

    positions=nx.circular_layout(g)
    
    # NODES
    nodes, color = zip(*nx.get_node_attributes(g, metric).items())
    nodes, label = zip(*nx.get_node_attributes(g, 'labels').items())
    nodes, size = zip(*nx.get_node_attributes(g, metric).items())
    new={}
    for x,y in nx.get_node_attributes(g, 'labels').items():
        new[x]=y['area']
    
    #draws nodes
    color = np.array(color)
    colz=stats.zscore(color)
    nColormap=plt.cm.cool 
    cM=colz.max()
    cm=colz.min()

    scale=scl/colz.max()
    nx.draw_networkx_nodes(g,
                             positions,
                             node_color=colz,
                             node_size=np.square(colz)*scale,
                             alpha=0.8,
                             cmap= nColormap,
                             vmin=cm ,vmax=cM)

    #Styling for labels
    nx.draw_networkx_labels(g, 
                            positions,
                            new,
                            font_size=FONT,
                            font_family='sans-serif',
                            fontweight = 'bold',
                            horizontalalignment = 'center',
                            verticalalignment = 'top')


    # EDGES 
    edges,weights = zip(*nx.get_edge_attributes(g, 'weight').items())
    #draw edges
    weights=np.array(weights)
    eColormap=plt.cm.gist_rainbow #check here if you want different colors https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html

    nx.draw_networkx_edges(g, 
                             positions,
                             edge_list=edges,
                             style='solid',
                             width = np.square(weights)*200,
                             edge_color = weights,
                             edge_cmap=eColormap,
                             edge_vmin=weights.min(),
                             edge_vmax=weights.max())
    
    #FInishing touches


    plt.axis('off')
    if bmi == 'no':
        plt.title("%s and edge weights of \n %s graph"%(metric, 'Average BMI'), fontsize = FONT)
    if bmi == 'ov':
        plt.title("%s and edge weights of \n %s graph"%(metric, 'High BMI'), fontsize = FONT)
    if bmi == 'ob':
        plt.title("%s and edge weights of \n %s graph"%(metric, 'Very high BMI'), fontsize = FONT)
    

    axins1 = inset_axes(ax1,
                    width="2.5%",  # width = 50% of parent_bbox width
                    height="100%",  # height : 5%
                    loc='right',
                    bbox_to_anchor=(0.15, 0., 1, 1), #(x0, y0, width, height)
                    bbox_transform=ax1.transAxes,
                    borderpad=1)
    
    axins2 = inset_axes(ax1,
                    width="2.5%",  # width = 50% of parent_bbox width
                    height="100%",  # height : 5%
                    loc='right',
                    bbox_to_anchor=(.25, 0, 1, 1),
                    bbox_transform=ax1.transAxes,
                    borderpad=1)

    sm = plt.cm.ScalarMappable(cmap=eColormap, norm=plt.Normalize(vmin = weights.min(), vmax=weights.max()))
    sm._A = []

    edge_bar=fig.colorbar(sm, cax=axins1, orientation="vertical")
    for l in edge_bar.ax.yaxis.get_ticklabels():
        l.set_size(FONT)
    edge_bar.set_label('Strength of edge weight', fontsize = FONT)
    
    sn = plt.cm.ScalarMappable(cmap=nColormap, norm=plt.Normalize(vmin = cm, vmax=cM))
    sn._A = []
    
    rgb = sn.to_rgba(x=colz)
    save={}
    i = 0
    for x,y in nx.get_node_attributes(g, 'labels').items():
        save[x]=[y['IC'], y['area'], np.round(rgb[i]*255)]
        i=i+1
    
    node_bar=fig.colorbar(sn, cax=axins2, label='Module value')
    for l in node_bar.ax.yaxis.get_ticklabels():
        l.set_size(FONT)
    node_bar.set_label('%s'%metric,fontsize = FONT)
    
    
    basepath='/Users/gracer/Google Drive/HCP/HCP_graph/1200/images'
    if bmi == 'no':
        plt.savefig(os.path.join(basepath,"%s_%s_%s.png"%(metric, 'Average BMI', mod)), format="PNG")
    if bmi == 'ov':
        plt.savefig(os.path.join(basepath,"%s_%s_%s.png"%(metric, 'High BMI', mod)), format="PNG")
    if bmi == 'ob':
        plt.savefig(os.path.join(basepath,"%s_%s_%s.png"%(metric, 'Very high BMI', mod)), format="PNG")
    plt.show()
    return(save)


In [38]:
wb_con = {
    'no':{2:{},5:{}},
    'ov': {2:{}, 6:{}},
    'ob':{4:{}, 6:{}}
}

for group, mods in wb_con.items():
    print(group)
    for mod, blank in mods.items():
        print(mod)  
        wb_con[group][mod]=basic_graph(subgraph_dict[group][mod], 50000, 50, 'PC', (75,50), 80, basepath, '%s'%group, '%i'%mod)

no
2
5
ov
2
6
ob
4
6


## Get the colors for workbench

In [39]:
for group, mods in wb_con.items():
    print(group)
    for mod, data in mods.items():
        print(mod)
        writepath = os.path.join(basepath,'%s_%i.txt'%(group, mod))
        f = open(writepath, "w")
        for key, value in data.items():
            print(key)
            x = value[2]
            print(x)
            f.write('LABEL_%i\n'%(key+1))
            f.write('%i %i %i %i %i\n'%(key+1, x[0], x[1], x[2], x[3]))
        f.close()

no
2
2
[163.  92. 255. 255.]
3
[  4. 251. 255. 255.]
7
[ 47. 208. 255. 255.]
10
[  0. 255. 255. 255.]
12
[ 36. 219. 255. 255.]
15
[ 71. 184. 255. 255.]
16
[ 16. 239. 255. 255.]
17
[255.   0. 255. 255.]
18
[179.  76. 255. 255.]
19
[102. 153. 255. 255.]
20
[ 83. 172. 255. 255.]
22
[112. 143. 255. 255.]
26
[120. 135. 255. 255.]
27
[ 18. 237. 255. 255.]
29
[ 48. 207. 255. 255.]
33
[109. 146. 255. 255.]
34
[108. 147. 255. 255.]
37
[125. 130. 255. 255.]
40
[ 83. 172. 255. 255.]
42
[ 86. 169. 255. 255.]
44
[ 37. 218. 255. 255.]
46
[ 57. 198. 255. 255.]
80
[105. 150. 255. 255.]
87
[191.  64. 255. 255.]
95
[  4. 251. 255. 255.]
96
[131. 124. 255. 255.]
5
64
[  0. 255. 255. 255.]
66
[243.  12. 255. 255.]
67
[208.  47. 255. 255.]
68
[123. 132. 255. 255.]
98
[133. 122. 255. 255.]
99
[148. 107. 255. 255.]
75
[ 46. 209. 255. 255.]
78
[134. 121. 255. 255.]
48
[255.   0. 255. 255.]
86
[160.  95. 255. 255.]
62
[156.  99. 255. 255.]
ov
2
2
[202.  53. 255. 255.]
3
[ 10. 245. 255. 255.]
7
[ 80. 175. 255. 

## Get ICnames

In [ ]:
g = subgraph_dict['ob'][6]
new={}
for x,y in nx.get_node_attributes(g, 'labels').items():
        new[x]=[y['IC'], y['area']]